### ISSUE TITLE
Batch File Processes

### ISSUE THREAD

**Issue by tatarize** [abey79/vpype#107] opened 2020-12-02 12:32 UTC
What if I don't *just* want to process the pipeline of a single document but I want to say process a thousand files? Let's say I have a 1000 files and I want to scale them all up by 50%. This would seem like a great tool to do that.

**Comment by abey79** [comment] 2020-12-02 14:12
Duplicate of #5 (which I'm reopening)

**Closed by abey79** 2020-12-02 14:12 UTC
