### ISSUE TITLE
write_svg - generate svg:path instead svg:polyline, svg:line, svg:polygon

### ISSUE THREAD

**Issue by vmario89** [abey79/vpype#246] opened 2021-04-04 13:29 UTC
Hi,
would it be possible to create svg:path elements in output instead using primitive elements to put out? i am integrating vpype into inkscape but the back-conversion from primitives to regular paths is tedious/really really slow.

**Comment by vmario89** [comment] 2021-04-04 16:08
I made a pull request to this feature: https://github.com/abey79/vpype/pull/247

**Comment by abey79** [comment] 2021-04-06 09:28
This appears to be a duplicate of #196. I used to have this feature and removed it at some point, thinking it was useless. It turns out that inkscape users have requested it for the same performance reasons. I'll take a look at the PR.

**Comment by vmario89** [comment] 2021-04-06 22:59
oh i did not know that it existed in the path. Some choice what the users want would be cool ;-)

**Comment by abey79** [comment] 2021-07-09 13:39
Closing since duplicate

**Closed by abey79** 2021-07-09 13:39 UTC
Labels: duplicate, enhancement
