### ISSUE TITLE
Calls to Length() remain despite deprecation

### ISSUE THREAD

**Issue by johnbentcope** [abey79/vpype#228] opened 2021-03-12 02:24 UTC
Running any vpype command results in at least one deprecation warning regarding calls to vpype.Length().

**Comment by abey79** [comment] 2021-03-12 08:14
I can't reproduce. Can you tell me more about your setup, vpype version, installed plug-ins?

**Comment by johnbentcope** [comment] 2021-03-12 16:02
I have installed vpype 1.6.0, and vpype-gcode 0.7.1. I am running Ubuntu 20.10, I've not installed with a virtual environment, and any calls to vpype display the warning, including `vpype --version`

```WARNING:root:!!! `vpype.Length` is deprecated, use `vpype.LengthType` instead.```

**Comment by abey79** [comment] 2021-03-13 08:33
I'm not able to reproduce. Can you show the full output of `vpype --help`?

**Comment by johnbentcope** [comment] 2021-03-19 16:48
```
WARNING:root:!!! `vpype.Length` is deprecated, use `vpype.LengthType` instead.
Usage: vpype [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...

  Execute the vector processing pipeline passed as argument.

Options:
  --version           Show the version and exit.
  -v, --verbose
  -I, --include PATH  Load commands from a command file.
  -H, --history       Record this command in a `vpype_history.txt` in the
                      current directory.

  -s, --seed INTEGER  Specify the RNG seed.
  -c, --config PATH   Load an additional config file.
  --help              Show this message and exit.

Commands:

  Primitives:
    arc           Generate lines approximating a circular arc.
    circle        Generate lines approximating a circle.
    ellipse       Generate lines approximating an ellipse.
    line          Generate a single line.
    rect          Generate a rectangle, with optional rounded angles.

  Block control:
    begin         Marks the start of a block.
    end           Marks the end of a block.

  Operations:
    crop          Crop the geometries.
    filter        Filter paths according to specified criterion.
    layout        Layout the geometries on the provided page size.
    linemerge     Merge lines whose endings and starts overlap or are very...
    linesimplify  Reduce the number of segments in the geometries.
    linesort      Sort lines to minimize the pen-up travel distance.
    multipass     Add multiple passes to each line Each line is extended with...
    pagesize      Change the current page size.
    reloop        Randomize the seam location of closed paths.
    reverse       Reverse order of lines.
    snap          Snap all points to a grid with with a spacing of PITCH.
    splitall      Split all paths into their constituent segments.
    trim          Trim the geometries by some margin.

  Generators:
    frame         Add a single-line frame around the geometry.
    random        Generate random lines.

  Block processors:
    grid          Arrange generated geometries on a NxM grid.
    repeat        Stack geometries generated by the block N times on top of...

  Output:
    gwrite      
    show          Display the geometry in an graphical user interface.
    stat          Print human-readable statistics on the current geometries.
    write         Save geometries to a file.

  Layers:
    lcopy         Copy the content of one or more layer(s) to another layer.
    ldelete       Delete one or more layers.
    lmove         Move the content of one or more layer(s) to another layer.

  Plugins:
    occult        Remove occulted lines.

  Input:
    read          Extract geometries from a SVG file.
    script        Call an external python script to generate geometries.

  Transforms:
    rotate        Rotate the geometries (clockwise positive).
    scale         Scale the geometries by a factor.
    scaleto       Scale the geometries to given dimensions.
    skew          Skew the geometries.
    translate     Translate the geometries.

  Filters:
    squiggles     Apply a squiggle filter to the geometries.

  Text:
    text          Generate text using Hershey fonts.

```

**Comment by abey79** [comment] 2021-03-20 08:40
My best bet is that you have an outdated version of occult or gwrite installed.

Try:
```
pip install -U git+https://github.com/abey79/occult.git#egg=occult
pip install -U vpype-gcode
```

**Comment by johnbentcope** [comment] 2021-03-21 18:40
I don't doubt it. Those pip updates did not resolve the issue. This can be closed if it's an installation problem on my machine.

**Comment by abey79** [comment] 2021-03-21 20:38
Maybe an old version of vpype-text? What's the output of `pip freeze`?

**Comment by abey79** [comment] 2022-07-02 09:42
I'm closing this because it's likely not a vpype-related issue (rather a plug-in problem).

**Closed by abey79** 2022-07-02 09:42 UTC
